version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pgp_app
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html/
    networks:
      - dockerdb_default
